// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcL_2KwqBGb55DJ-EneQVLGdNVhaZtmIA',
    appId: '1:1037728522849:web:bc9b16d83ccc4a934dc020',
    messagingSenderId: '1037728522849',
    projectId: 'cceapp-2022',
    authDomain: 'cceapp-2022.firebaseapp.com',
    storageBucket: 'cceapp-2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjCzwcQZUnIRRIZFMuCdPTDi-EvBadrqQ',
    appId: '1:1037728522849:android:63aeb033251ead464dc020',
    messagingSenderId: '1037728522849',
    projectId: 'cceapp-2022',
    storageBucket: 'cceapp-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjXs0vUDv4fL2K8AN5XpR4QRQP5wb8bXg',
    appId: '1:1037728522849:ios:04e299329debcaa14dc020',
    messagingSenderId: '1037728522849',
    projectId: 'cceapp-2022',
    storageBucket: 'cceapp-2022.appspot.com',
    iosBundleId: 'com.example.cceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjXs0vUDv4fL2K8AN5XpR4QRQP5wb8bXg',
    appId: '1:1037728522849:ios:7ae591b4d7e8ee9f4dc020',
    messagingSenderId: '1037728522849',
    projectId: 'cceapp-2022',
    storageBucket: 'cceapp-2022.appspot.com',
    iosBundleId: 'com.example.cceapp.RunnerTests',
  );
}
